#! /bin/bash
# use after mininal install add "desktop" argument for desktop use
#not tested
MYUSER=user
SSID=
PASSWORD=

clear

#root config
sudo su

#french parameters
echo "4 - I3 - Generic - France - Finish"
sleep 5s
echo "4 - I1 - FR.UTF8 - Finish"
sleep 5s
raspi-config

#root password
passwd

#repository of the current version

#set wifi
echo "
network={
ssid="$SSID"
psk="$PASSWORD"
key_mgmt=WPA-PSK
}" >> /etc/wpa_supplicant/wpa_supplicant.conf
service ifup@wlan0 restart
sleep 15s

#allow sudo to user
apt-get update -y
apt install -y sudo
adduser $MYUSER sudo
usermod -a -G video $MYUSER

#delete pi
deluser --remove-home pi

#install and config of the firewall
apt install -y ufw
sed -i 's/IPV6=yes/IPV6=no/g' /etc/default/ufw
ufw enable
ufw default deny incoming
ufw default deny outgoing
ufw allow out 80/tcp
ufw allow out 443/tcp
ufw allow out 53/udp
ufw allow out 123

#log management for sd card
echo "
tmpfs /tmp tmpfs defaults,noatime,nosuid,size=100m 0 0
tmpfs /var/tmp tmpfs defaults,noatime,nosuid,size=30m 0 0" >> /etc/fstab

#install my softwares
apt update -y
myprogram="
antiword
bc
bmon
bwm-ng
calcurse
curl
ethstatus
gpm
htop
imagemagick
inxi
iw
jp2a
links2
mc
moc
ncdu
nmon
numlockx
ntp
ntpdate
odt2txt
pstotext
python3-gpiozero
raspi-gpio
rpi-update
screenfetch
sense-hat
tor
txt2html
unhtml
youtube-dl
wicd-curses"
apt install -y $myprogram

ntpdate fr.pool.ntp.org

#create my own folders
cd /home/$MYUSER/
rmdir *

for myfolder in "
Documents
Downloads
Transferts
Medias
Unclear"
do
  sudo -u $MYUSER mkdir /home/$MYUSER/$myfolder
done

#personnal commands
echo "
#personnal commands

mkcd() {
    mkdir -p "$1" ; cd -P "$1"
}

command_not_found_handle () {
    echo "Hello Stupid ¯\_(ツ)_/¯ !";
}

alias ll='ls -lasFh --color=auto'
alias ls='ls --color=auto'
alias meteo='wget wttr.in/poitiers -O - -o /dev/null'
alias csv='column -s ',' -t'
alias upg='sudo apt update && sudo apt -V upgrade && sudo apt-get autoremove -y && sudo apt-get clean'
alias radio='mpv --vid=no https://www.youtube.com/watch?v=AQBh9soLSkI'

" >> /home/$MYUSER/.bashrc

#change computer name
echo 'computerrasp' > /etc/hostname

#boot display screensaver audio
echo 'disable_overscan=1
overscan_left=4
overscan_right=4
overscan_top=4
overscan_bottom=4
consoleblank=0
hdmi_group=1
hdmi_mode=16
hdmi_drive=2
dtparam_audio=on
gpu_mem=64' > /boot/config.txt
# echo 'hdmi_safe=1' >> /boot/config.txt

#full upgrade
apt update -y
rpi-update -y
apt upgrade -y
apt dist-upgrade -y
apt autoremove -y
apt autoclean -y
echo "---------------END---------------"
#reboot

#install test for desktop
if [ "$1" = desktop ]
then
apt update -y
desktopprogram="
acl
acpi
acpi-support-base
acpid
adduser
adwaita-icon-theme
alacarte
alsa-base
alsa-utils
amd64-microcode
apt
apt-listchanges
apt-transport-https
apt-utils
aspell
aspell-en
atmel-firmware
avahi-daemon
base-files
base-passwd
bash
bash-completion
bind9-host
binutils
blt
bluez
bluez-firmware
broadcom-sta-dkms
bsdmainutils
bsdutils
build-essential
busybox
bzip2
ca-certificates
chromium
cifs-utils
coinor-libcbc3
coinor-libcgl1
coinor-libclp1
coinor-libcoinmp1
coinor-libcoinutils3
coinor-libosi1
console-setup
console-setup-linux
coreutils
cpio
cpp
cpp-4.8
cpp-4.9
crda
cron
cryptsetup-bin
cups-bsd
cups-client
cups-common
curl
dahdi-firmware-nonfree
dash
dbus
dbus-x11
dc
dconf-gsettings-backend
dconf-service
debconf
debconf-i18n
debconf-utils
debian-archive-keyring
debian-reference-common
debian-reference-en
debianutils
desktop-base
desktop-file-utils
dh-python
dhcpcd5
dictionaries-common
diffutils
dkms
dmidecode
dmsetup
dosfstools
dphys-swapfile
dpkg
dpkg-dev
e2fslibs
e2fsprogs
ed
eject
emacsen-common
esound-common
fakeroot
fbset
file
findutils
firmware-adi
firmware-atheros
firmware-bnx2
firmware-bnx2x
firmware-brcm80211
firmware-crystalhd
firmware-intelwimax
firmware-ipw2x00
firmware-ivtv
firmware-iwlwifi
firmware-libertas
firmware-linux
firmware-linux-free
firmware-linux-nonfree
firmware-myricom
firmware-netxen
firmware-qlogic
firmware-ralink
firmware-realtek
firmware-samsung
firmware-ti-connectivity
firmware-zd1211
fontconfig
fontconfig-config
fontconfig-infinality
fonts-dejavu
fonts-dejavu-core
fonts-dejavu-extra
fonts-droid
fonts-freefont-ttf
fonts-opensymbol
fonts-roboto
fonts-sil-gentium-basic
freepats
fuse
g++
g++-4.9
galculator
gcc
gcc-4.8
gcc-4.8-base
gcc-4.9
gcc-4.9-base
gconf-service
gconf2
gconf2-common
gdb
gdbserver
gdebi-core
geoip-database
gettext-base
giblib1
gir1.2-atk-1.0
gir1.2-freedesktop
gir1.2-gdkpixbuf-2.0
gir1.2-glib-2.0
gir1.2-gmenu-3.0
gir1.2-gtk-3.0
gir1.2-pango-1.0
git
git-man
gksu
glib-networking
glib-networking-common
glib-networking-services
gnome-icon-theme
gnome-icon-theme-symbolic
gnome-menus
gnome-themes-standard-data
gnupg
gnupg-agent
gnupg2
gpgv
gpicview
grep
groff-base
gsettings-desktop-schemas
gsfonts
gsfonts-x11
gstreamer0.10-alsa
gstreamer0.10-plugins-base
gstreamer1.0-alsa
gstreamer1.0-libav
gstreamer1.0-plugins-bad
gstreamer1.0-plugins-base
gstreamer1.0-plugins-good
gstreamer1.0-x
gtk2-engines
gtk2-engines-clearlookspix
gtk2-engines-pixbuf
gvfs
gvfs-backends
gvfs-common
gvfs-daemons
gvfs-fuse
gvfs-libs
gzip
hardlink
hdparm
hicolor-icon-theme
hostname
i2c-tools
i965-va-driver
idle
idle-python2.7
idle-python3.4
idle3
ifupdown
init
init-system-helpers
initramfs-tools
initscripts
insserv
intel-microcode
iproute2
iptables
iputils-ping
irqbalance
isc-dhcp-client
isc-dhcp-common
iso-codes
iucode-tool
iw
jackd
jackd2
jackd2-firewire
java-common
javascript-common
kbd
keyboard-configuration
klibc-utils
kmod
leafpad
less
libaa1
libabw-0.1-1
libacl1
libalgorithm-c3-perl
libalgorithm-diff-perl
libalgorithm-diff-xs-perl
libalgorithm-merge-perl
libapt-inst1.5
libapt-pkg4.12
libarchive-extract-perl
libarchive13
libasan0
libasan1
libasound2
libasound2-data
libasound2-plugins
libaspell15
libasprintf0c2
libass5
libassuan0
libasyncns0
libatasmart4
libatk-bridge2.0-0
libatk1.0-0
libatk1.0-data
libatomic1
libatspi2.0-0
libattr1
libaudio2
libaudiofile1
libaudit-common
libaudit1
libavahi-client3
libavahi-common-data
libavahi-common3
libavahi-core7
libavahi-glib1
libavc1394-0
libavcodec56
libavformat56
libavresample2
libavutil54
libbind9-90
libblas-common
libblas3
libblkid1
libbluetooth3
libbluray1
libboost-atomic1.55.0
libboost-date-time1.55.0
libboost-filesystem1.55.0
libboost-iostreams1.55.0
libboost-program-options1.55.0
libboost-regex1.55.0
libboost-system1.55.0
libboost-thread1.55.0
libbsd0
libburn4
libbz2-1.0
libc-bin
libc-dev-bin
libc6
libc6-dbg
libc6-dev
libc6-i686
libcaca0
libcairo-gobject2
libcairo2
libcanberra-gtk3-0
libcanberra0
libcap-ng0
libcap2
libcap2-bin
libcdio-cdda1
libcdio-paranoia1
libcdio13
libcdparanoia0
libcdr-0.1-1
libcgi-fast-perl
libcgi-pm-perl
libchromaprint0
libcilkrts5
libclass-c3-perl
libclass-c3-xs-perl
libcloog-isl4
libclucene-contribs1
libclucene-core1
libcmis-0.4-4
libcolamd2.8.0
libcolord2
libcomerr2
libcompfaceg1
libconfig++9
libcpan-meta-perl
libcroco3
libcryptsetup4
libcups2
libcupsfilters1
libcupsimage2
libcurl3
libcurl3-gnutls
libcwiid1
libdaemon0
libdata-optlist-perl
libdata-section-perl
libdatrie1
libdb5.3
libdbus-1-3
libdbus-glib-1-2
libdc1394-22
libdca0
libdconf1
libdebconfclient0
libdevmapper-event1.02.1
libdevmapper1.02.1
libdirectfb-1.2-9
libdns-export100
libdns100
libdpkg-perl
libdrm-intel1
libdrm-nouveau2
libdrm-radeon1
libdrm2
libdv4
libdvdnav4
libdvdread4
libe-book-0.1-1
libedit2
libegl1-mesa
libegl1-mesa-drivers
libelf1
libelfg0
libenca0
libenchant1c2a
libeot0
libepoxy0
liberror-perl
libesd0
libestr0
libetonyek-0.1-1
libetpan17
libevdev2
libevent-2.0-5
libexif12
libexpat1
libexpat1-dev
libexttextcat-2.0-0
libexttextcat-data
libfaad2
libfakeroot
libfcgi-perl
libffado2
libffi6
libfftw3-double3
libfftw3-single3
libfile-fcntllock-perl
libflac8
libflite1
libfltk1.3
libfluidsynth1
libfm-data
libfm-extra4
libfm-gtk-data
libfm-gtk4
libfm-modules
libfm4
libfontconfig1
libfontenc1
libfreehand-0.1-1
libfreetype6
libfreetype6-dev
libfribidi0
libfuse2
libgbm1
libgcc-4.8-dev
libgcc-4.9-dev
libgcc1
libgconf-2-4
libgcrypt20
libgd3
libgdbm3
libgdk-pixbuf2.0-0
libgdk-pixbuf2.0-common
libgeoip1
libgfortran3
libgif4
libgirepository-1.0-1
libgksu2-0
libgl1-mesa-dri
libgl1-mesa-glx
libglapi-mesa
libgles1-mesa
libgles2-mesa
libglew1.10
libglib2.0-0
libglib2.0-bin
libglib2.0-data
libglibmm-2.4-1c2a
libgltf-0.0-0
libglu1-mesa
libgme0
libgmp10
libgnome-keyring-common
libgnome-keyring0
libgnome-menu-3-0
libgnutls-deb0-28
libgnutls-openssl27
libgoa-1.0-0b
libgoa-1.0-common
libgomp1
libgpg-error0
libgpgme11
libgphoto2-6
libgphoto2-port10
libgpm2
libgraphite2-3
libgsm1
libgssapi-krb5-2
libgstreamer-plugins-bad1.0-0
libgstreamer-plugins-base0.10-0
libgstreamer-plugins-base1.0-0
libgstreamer0.10-0
libgstreamer1.0-0
libgtk-3-0
libgtk-3-bin
libgtk-3-common
libgtk2.0-0
libgtk2.0-bin
libgtk2.0-common
libgtkglext1
libgtop2-7
libgtop2-common
libgudev-1.0-0
libharfbuzz-icu0
libharfbuzz0b
libhogweed2
libhsqldb1.8.0-java
libhunspell-1.3-0
libhyphen0
libice6
libicu52
libid3tag0
libidn11
libiec61883-0
libilmbase6
libimlib2
libimobiledevice4
libirs-export91
libisc-export95
libisc95
libisccc90
libisccfg-export90
libisccfg90
libisl10
libisoburn1
libisofs6
libitm1
libiw30
libjack-jackd2-0
libjasper1
libjavascriptcoregtk-3.0-0
libjbig0
libjim0.75
libjpeg62-turbo
libjs-jquery
libjs-prettify
libjs-sphinxdoc
libjs-underscore
libjson-c2
libjson-glib-1.0-0
libjson-glib-1.0-common
libjte1
libk5crypto3
libkate1
libkeyutils1
libklibc
libkmod2
libkrb5-3
libkrb5support0
libksba8
liblangtag-common
liblangtag1
liblapack3
liblcms2-2
libldap-2.4-2
libldb1
liblightdm-gobject-1-0
libllvm3.5
liblocale-gettext-perl
liblockfile-bin
liblockfile1
liblog-message-perl
liblog-message-simple-perl
liblogging-stdlog0
liblognorm1
libltdl7
libluajit-5.1-common
liblvm2app2.2
liblwres90
liblzma5
liblzo2-2
libmad0
libmagic1
libmenu-cache-bin
libmenu-cache3
libmhash2
libmikmod3
libmimic0
libmjpegutils-2.1-0
libmms0
libmng1
libmnl0
libmodplug1
libmodule-build-perl
libmodule-pluggable-perl
libmodule-signature-perl
libmotif-common
libmount1
libmozjs185-1.0
libmp3lame0
libmpc3
libmpdec2
libmpeg2encpp-2.1-0
libmpfr4
libmpg123-0
libmplex2-2.1-0
libmro-compat-perl
libmspub-0.1-1
libmtdev1
libmtp-common
libmtp9
libmwaw-0.3-3
libmythes-1.2-0
libncurses5
libncursesw5
libneon27-gnutls
libnetfilter-acct1
libnettle4
libnewt0.52
libnfnetlink0
libnfsidmap2
libnl-3-200
libnl-genl-3-200
libnotify4
libnspr4
libnss-mdns
libnss-myhostname
libnss3
libntdb1
libnuma1
libobrender29
libobt2
libodfgen-0.1-1
libofa0
libogg0
libopenal-data
libopenal1
libopencv-calib3d2.4
libopencv-contrib2.4
libopencv-core2.4
libopencv-features2d2.4
libopencv-flann2.4
libopencv-highgui2.4
libopencv-imgproc2.4
libopencv-legacy2.4
libopencv-ml2.4
libopencv-objdetect2.4
libopencv-video2.4
libopenexr6
libopenjpeg5
libopenvg1-mesa
libopts25
libopus0
liborc-0.4-0
liborcus-0.8-0
libp11-kit0
libpackage-constants-perl
libpackagekit-glib2-18
libpam-chksshpwd
libpam-modules
libpam-modules-bin
libpam-runtime
libpam-systemd
libpam0g
libpango-1.0-0
libpango1.0-0
libpangocairo-1.0-0
libpangoft2-1.0-0
libpangox-1.0-0
libpangoxft-1.0-0
libparams-util-perl
libparted2
libpci3
libpciaccess0
libpcre3
libpcsclite1
libpipeline1
libpisock9
libpixman-1-0
libplist2
libplymouth4
libpng12-0
libpng12-dev
libpod-latex-perl
libpod-readme-perl
libpolkit-agent-1-0
libpolkit-backend-1-0
libpolkit-gobject-1-0
libpoppler46
libpopt0
libportmidi0
libprocps3
libproxy1
libpsl0
libpth20
libpulse0
libpulsedsp
libpython-stdlib
libpython2.7
libpython2.7-minimal
libpython2.7-stdlib
libpython3-dev
libpython3-stdlib
libpython3.4
libpython3.4-dev
libpython3.4-minimal
libpython3.4-stdlib
libqscintilla2-11
libqscintilla2-l10n
libqt4-dbus
libqt4-network
libqt4-opengl
libqt4-xml
libqt4-xmlpatterns
libqtcore4
libqtdbus4
libqtgui4
libqtwebkit4
libquadmath0
libraptor2-0
librasqal3
libraw1394-11
librdf0
libreadline6
libregexp-common-perl
librest-0.7-0
librevenge-0.0-0
librsvg2-2
librsvg2-common
librtmp1
libruby2.1
libsamplerate0
libsasl2-2
libsasl2-modules
libsasl2-modules-db
libsbc1
libschroedinger-1.0-0
libscsynth1
libsdl-image1.2
libsdl-mixer1.2
libsdl-ttf2.0-0
libsdl1.2debian
libsecret-1-0
libsecret-common
libselinux1
libsemanage-common
libsemanage1
libsepol1
libservlet2.5-java
libsgutils2-2
libshout3
libsigc++-2.0-0c2a
libslang2
libsm6
libsmartcols1
libsmbclient
libsndfile1
libsoftware-license-perl
libsoundtouch0
libsoup-gnome2.4-1
libsoup2.4-1
libspandsp2
libspeex1
libspeexdsp1
libsqlite3-0
libsrtp0
libss2
libssh2-1
libssl1.0.0
libstartup-notification0
libstdc++-4.9-dev
libstdc++6
libsub-exporter-perl
libsub-install-perl
libswscale3
libsysfs2
libsystemd0
libtag1-vanilla
libtag1c2a
libtalloc2
libtasn1-6
libtbb2
libtcl8.6
libtdb1
libterm-ui-perl
libtevent0
libtext-charwidth-perl
libtext-iconv-perl
libtext-soundex-perl
libtext-template-perl
libtext-wrapi18n-perl
libthai-data
libthai0
libtheora0
libtiff5
libtimedate-perl
libtinfo5
libtirpc1
libtk8.6
libtxc-dxtn-s2tc0
libubsan0
libudev1
libudisks2-0
libusb-0.1-4
libusb-1.0-0
libusbmuxd2
libustr-1.0-1
libuuid-perl
libuuid1
libv4l-0
libv4l2rds0
libv4lconvert0
libva1
libvdpau1
libvisio-0.1-1
libvisual-0.4-0
libvisual-0.4-plugins
libvo-aacenc0
libvo-amrwbenc0
libvorbis0a
libvorbisenc2
libvorbisfile3
libvpx1
libvte-common
libvte9
libwavpack1
libwayland-client0
libwayland-cursor0
libwayland-egl1-mesa
libwayland-server0
libwbclient0
libwebkitgtk-3.0-0
libwebkitgtk-3.0-common
libwebp5
libwebpdemux1
libwebpmux1
libwebrtc-audio-processing-0
libwildmidi-config
libwildmidi1
libwnck-common
libwnck22
libwpd-0.10-10
libwpg-0.3-3
libwps-0.3-3
libwrap0
libx11-6
libx11-data
libx11-xcb1
libx264-142
libxatracker2
libxau6
libxaw7
libxcb-dri2-0
libxcb-dri3-0
libxcb-glx0
libxcb-present0
libxcb-render0
libxcb-shape0
libxcb-shm0
libxcb-sync1
libxcb-util0
libxcb-xfixes0
libxcb1
libxcomposite1
libxcursor1
libxdamage1
libxdmcp6
libxext6
libxfce4util-bin
libxfce4util-common
libxfce4util6
libxfconf-0-2
libxfixes3
libxfont1
libxft2
libxi6
libxinerama1
libxkbcommon0
libxkbfile1
libxklavier16
libxm4
libxml++2.6-2
libxml2
libxmu6
libxmuu1
libxpm4
libxrandr2
libxrender1
libxres1
libxshmfence1
libxslt1.1
libxss1
libxt6
libxtables10
libxtst6
libxv1
libxvidcore4
libxvmc1
libxxf86dga1
libxxf86vm1
libyajl2
libyaml-0-2
libzbar0
lightdm
lightdm-gtk-greeter
linux-base
live-tools
locales
login
logrotate
lp-solve
lsb-base
lsb-release
lua5.1
luajit
lxappearance
lxappearance-obconf
lxde
lxde-common
lxde-core
lxde-icon-theme
lxinput
lxkeymap
lxmenu-data
lxpanel
lxpanel-data
lxrandr
lxsession
lxtask
lxterminal
make
man-db
manpages
manpages-dev
mawk
menu-xdg
mime-support
module-init-tools
mount
multiarch-support
nano
ncdu
ncurses-base
ncurses-bin
ncurses-term
net-tools
netbase
netcat-traditional
netsurf-common
netsurf-gtk
nfacct
nfs-common
ntfs-3g
ntp
nuscratch
openbox
openssh-client
openssh-server
openssh-sftp-server
openssl
oracle-java8-jdk
os-prober
packagekit
parted
passwd
patch
pciutils
pcmanfm
perl
perl-base
perl-modules
pi-bluetooth
pi-greeter
pi-package
pi-package-data
pi-package-session
piclone
pigpio
pimixer
pinentry-gtk2
pipanel
pishutdown
pkg-config
plymouth
plymouth-themes
point-rpi
policykit-1
poppler-data
poppler-utils
powermgmt-base
pprompt
prism2-usb-firmware-installer
procps
psmisc
pulseaudio
pulseaudio-module-bluetooth
pulseaudio-module-x11
pulseaudio-utils
pypy
pypy-lib
python
python-apt
python-apt-common
python-blinker
python-cairo
python-cffi
python-chardet
python-chardet-whl
python-colorama
python-colorama-whl
python-cryptography
python-dbus
python-dbus-dev
python-distlib
python-distlib-whl
python-flask
python-fourletterphat
python-gi
python-gobject
python-gobject-2
python-gpiozero
python-gtk2
python-html5lib
python-html5lib-whl
python-itsdangerous
python-jinja2
python-markupsafe
python-microdotphat
python-minimal
python-ndg-httpsclient
python-numpy
python-openssl
python-picraft
python-pifacecommon
python-pifacedigitalio
python-piglow
python-pigpio
python-pil
python-pip
python-pip-whl
python-pkg-resources
python-ply
python-pyasn1
python-pycparser
python-pygame
python-pyinotify
python-requests
python-requests-whl
python-scrollphat
python-scrollphathd
python-sense-emu
python-sense-emu-doc
python-serial
python-setuptools
python-setuptools-whl
python-six
python-six-whl
python-smbus
python-sn3218
python-spidev
python-support
python-talloc
python-tk
python-twython
python-urllib3
python-urllib3-whl
python-werkzeug
python-wheel
python-xklavier
python2.7
python2.7-minimal
python3
python3-apt
python3-cffi
python3-chardet
python3-codebug-i2c-tether
python3-codebug-tether
python3-colorama
python3-cryptography
python3-debian
python3-dev
python3-distlib
python3-flask
python3-fourletterphat
python3-gi
python3-gpiozero
python3-html5lib
python3-itsdangerous
python3-jedi
python3-jinja2
python3-markupsafe
python3-microdotphat
python3-minimal
python3-numpy
python3-openssl
python3-pgzero
python3-picraft
python3-pifacecommon
python3-pifacedigital-scratch-handler
python3-pifacedigitalio
python3-piglow
python3-pigpio
python3-pil
python3-pip
python-picamera
python3-picamera
python-picamera-docs
python3-pkg-resources
python3-ply
python3-pycparser
python3-pyinotify
python3-requests
python3-scrollphat
python3-scrollphathd
python3-sense-emu
python3-serial
python3-setuptools
python3-six
python3-smbus
python3-sn3218
python3-spidev
python3-thonny
python3-tk
python3-twython
python3-uno
python3-urllib3
python3-venv
python3-werkzeug
python3-wheel
python3.4
python3.4-dev
python3.4-minimal
python3.4-venv
qdbus
qjackctl
qtchooser
qtcore4-l10n
raspberrypi-artwork
raspberrypi-net-mods
raspberrypi-sys-mods
raspberrypi-ui-mods
raspi-config
raspi-gpio
rc-gui
readline-common
rename
resolvconf
rfkill
rpcbind
rpd-icons
rpd-plym-splash
rpd-wallpaper
rpi-chromium-mods
rpi-update
rsync
rsyslog
rtkit
ruby
ruby2.1
rubygems-integration
samba-common
samba-libs
scrot
sed
sense-emu-tools
sensible-utils
sgml-base
shared-mime-info
squeak-plugins-scratch
squeak-vm
ssh
startpar
strace
supercollider
supercollider-common
supercollider-ide
supercollider-language
supercollider-server
supercollider-supernova
systemd
systemd-sysv
sysv-rc
sysvinit-utils
tar
tasksel
tasksel-data
tcpd
timidity
tk8.6-blt2.5
traceroute
tree
triggerhappy
tzdata
ucf
udev
udisks
udisks2
uno-libs3
unzip
ure
usb-modeswitch
usb-modeswitch-data
usbutils
user-setup
util-linux
uuid-runtime
v4l-utils
va-driver-all
vdpau-va-driver
vim-common
vim-tiny
wget
whiptail
wireless-regdb
wireless-tools
wpasupplicant
x11-common
x11-utils
x11-xkb-utils
x11-xserver-utils
x2x
xarchiver
xauth
xcompmgr
xdg-user-dirs
xdg-utils
xfconf
xfonts-100dpi
xfonts-base
xfonts-encodings
xfonts-utils
xinit
xkb-data
xml-core
xpdf
xserver-common
xserver-xorg
xserver-xorg-core
xserver-xorg-input-all
xserver-xorg-input-evdev
xserver-xorg-input-mouse
xserver-xorg-input-synaptics
xserver-xorg-input-vmmouse
xserver-xorg-input-wacom
xserver-xorg-video-all
xserver-xorg-video-ati
xserver-xorg-video-cirrus
xserver-xorg-video-fbdev
xserver-xorg-video-geode
xserver-xorg-video-intel
xserver-xorg-video-mach64
xserver-xorg-video-mga
xserver-xorg-video-modesetting
xserver-xorg-video-neomagic
xserver-xorg-video-nouveau
xserver-xorg-video-openchrome
xserver-xorg-video-qxl
xserver-xorg-video-r128
xserver-xorg-video-radeon
xserver-xorg-video-savage
xserver-xorg-video-siliconmotion
xserver-xorg-video-sisusb
xserver-xorg-video-tdfx
xserver-xorg-video-trident
xserver-xorg-video-vesa
xserver-xorg-video-vmware
xz-utils
zenity
zenity-common
zlib1g
zlib1g-dev"
apt install -y $desktopprogram
apt autoremove -y && apt autoclean -y