#!/bin/sh

# ufetch-centos - tiny system info for centos

## INFO

# user is already defined
host="$(hostname)"
os="$(cat /etc/centos-release | sed 's/release //')"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(yum list installed | wc -l)"
shell="$(basename "$SHELL")"

## UI DETECTION

if [ -n "${DE}" ]; then
	ui="${DE}"
	uitype='DE'
elif [ -n "${WM}" ]; then
	ui="${WM}"
	uitype='WM'
elif [ -n "${XDG_CURRENT_DESKTOP}" ]; then
	ui="${XDG_CURRENT_DESKTOP}"
	uitype='DE'
elif [ -n "${DESKTOP_SESSION}" ]; then
	ui="${DESKTOP_SESSION}"
	uitype='DE'
elif [ -f "${HOME}/.xinitrc" ]; then
	ui="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	uitype='WM'
elif [ -f "${HOME}/.xsession" ]; then
	ui="$(tail -n 1 "${HOME}/.xsession" | cut -d ' ' -f 2)"
	uitype='WM'
else
	ui='unknown'
	uitype='UI'
fi

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${magenta}"      # labels
nc="${reset}${bold}${magenta}"      # user and hostname
ic="${reset}${bold}${white}"        # info
c0="${reset}${bold}${green}"        # first color
c1="${reset}${bold}${yellow}"       # second color
c2="${reset}${bold}${magenta}"      # third color
c3="${reset}${bold}${blue}"         # fourth color

## OUTPUT

cat <<EOF

${c0}   ____${c1}^${c2}____   ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}   |\\  ${c1}|${c2}  /|   ${lc}OS:        ${ic}${os}${reset}
${c0}   | \\ ${c1}|${c2} / |   ${lc}KERNEL:    ${ic}${kernel}${reset}
${c2}  <---- ${c3}---->  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c3}   | / ${c0}|${c1} \\ |   ${lc}PACKAGES:  ${ic}${packages}${reset}
${c3}   |/__${c0}|${c1}__\\|   ${lc}SHELL:     ${ic}${shell}${reset}
${c0}       v       ${lc}${uitype}:        ${ic}${ui}${reset}

EOF
